# Gradle & Kotlin Configuration
org.gradle.jvmargs=-Xmx4096m -XX:+UseG1GC
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configuration-cache=false

kotlin.mpp.enableCInteropCommonization=true
kotlin.daemon.jvmargs=-Xmx2048m

android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.native.ignoreDisabledTargets=true
android.sync.suppressAgpWarnings=GENERIC

# Publication Information
VERSION_NAME=0.1.0-beta01
GROUP=io.github.galib

POM_URL=https://github.com/galib/foliate-kmp
POM_SCM_URL=https://github.com/galib/foliate-kmp
POM_SCM_CONNECTION=scm:git:git://github.com/galib/foliate-kmp.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://github.com/galib/foliate-kmp.git

POM_LICENSE_NAME=MIT License
POM_LICENSE_URL=https://opensource.org/licenses/MIT
POM_LICENSE_DIST=repo

POM_DEVELOPER_ID=galib
POM_DEVELOPER_NAME=Asadullahil Galib
